/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CButton {
        /**
          * The button label
         */
        "label": string;
    }
    interface CColor {
        /**
          * The color
         */
        "color": string;
    }
}
declare global {
    interface HTMLCButtonElement extends Components.CButton, HTMLStencilElement {
    }
    var HTMLCButtonElement: {
        prototype: HTMLCButtonElement;
        new (): HTMLCButtonElement;
    };
    interface HTMLCColorElement extends Components.CColor, HTMLStencilElement {
    }
    var HTMLCColorElement: {
        prototype: HTMLCColorElement;
        new (): HTMLCColorElement;
    };
    interface HTMLElementTagNameMap {
        "c-button": HTMLCButtonElement;
        "c-color": HTMLCColorElement;
    }
}
declare namespace LocalJSX {
    interface CButton {
        /**
          * The button label
         */
        "label"?: string;
    }
    interface CColor {
        /**
          * The color
         */
        "color"?: string;
    }
    interface IntrinsicElements {
        "c-button": CButton;
        "c-color": CColor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "c-button": LocalJSX.CButton & JSXBase.HTMLAttributes<HTMLCButtonElement>;
            "c-color": LocalJSX.CColor & JSXBase.HTMLAttributes<HTMLCColorElement>;
        }
    }
}
